name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on:
  push:
    branches:
      - master  # Déclenchement sur push dans main

jobs:
  build-and-deploy:
    runs-on: self-hosted  # Exécute sur ta VM

    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Connexion au registry privé de Minikube
        run: docker login 192.168.49.2:31543

      - name: Build et push de l’image
        run: |
          docker build -t 192.168.49.2:31543/cyberfolio:latest .
          docker push 192.168.49.2:31543/cyberfolio:latest

      - name: Déployer sur Minikube
        run: |
          kubectl apply -f k8s/deployment.yaml
