name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on:
  push:
    branches:
      - master  # Déclenchement sur push dans main

jobs:
  build-and-deploy:
    runs-on: self-hosted  # Exécute sur ta VM Minikube

    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Connexion au registry privé de Minikube
        run: echo "" | docker login 192.168.49.2:31543 --username admin --password-stdin

      - name: Build et push de l’image
        run: |
          docker build -t 192.168.49.2:31543/monapp:latest .
          docker push 192.168.49.2:31543/monapp:latest

      - name: Déployer sur Minikube
        run: |
          kubectl delete pod -l app=monapp || true  # Supprime le pod existant pour forcer le redéploiement
          kubectl apply -f k8s/deployment.yaml
